version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: sleep infinity
    networks:
      - azure-emulator-network
    depends_on:
      - servicebus-emulator
      - eventhub-emulator
      - azurite
      - sqlserver

  sqlserver:
    container_name: "${PROJECT_NAME:-scriban-poc}-sqlserver"
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      azure-emulator-network:
        aliases:
          - "sqlserver"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  servicebus-emulator:
    container_name: "${PROJECT_NAME:-scriban-poc}-servicebus"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    environment:
      SQL_SERVER: "${PROJECT_NAME:-scriban-poc}-sqlserver"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: ${ACCEPT_EULA}
      SQL_WAIT_INTERVAL: ${SQL_WAIT_INTERVAL}
    ports:
      - "5672:5672"
      - "5300:5300"
    volumes:
      - servicebus-data:/tmp/servicebus
      - "${SERVICEBUS_CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    depends_on:
      - sqlserver
    networks:
      azure-emulator-network:
        aliases:
          - "servicebus-emulator"

  eventhub-emulator:
    container_name: "${PROJECT_NAME:-scriban-poc}-eventhub"
    image: mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest
    pull_policy: always
    volumes:
      - "${EVENTHUB_CONFIG_PATH}:/Eventhubs_Emulator/ConfigFiles/Config.json"
    environment:
      - ACCEPT_EULA=Y
      - BLOB_SERVER="${PROJECT_NAME:-scriban-poc}-azurite"
      - METADATA_SERVER="${PROJECT_NAME:-scriban-poc}-azurite"
    ports:
      - "5673:5672"
      - "9092:9092"
      - "5301:5300"
    depends_on:
      - azurite
    networks:
      - azure-emulator-network

  azurite:
    container_name: "${PROJECT_NAME:-scriban-poc}-azurite"
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data
    networks:
      - azure-emulator-network

volumes:
  servicebus-data:
  azurite-data:
  sqlserver-data:

networks:
  azure-emulator-network: