version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: sleep infinity
    networks:
      - azure-emulator-network
    depends_on:
      - servicebus-emulator
      - eventhub-emulator
      - azurite
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - azure-emulator-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q \"SELECT 1\""] # <--- Corrected line
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    environment:
      # Service Bus Emulator Configuration
      - ACCEPT_EULA=Y
      - SERVICEBUS_EMULATOR_CONFIG_PATH=/ServiceBus_Emulator/ConfigFiles/Config.json
      # SQL Server connection configuration
      - SqlServer__Server=sqlserver
      - SqlServer__Database=ServiceBusEmulatorDB
      - SqlServer__Username=sa
      - SqlServer__Password=${MSSQL_SA_PASSWORD}
    ports:
      - "5672:5672"  # AMQP protocol
      - "5300:5300"  # Management endpoint
    volumes:
      - servicebus-data:/tmp/servicebus
      - "${SERVICEBUS_CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    depends_on:
      - sqlserver
    networks:
      - azure-emulator-network

  eventhub-emulator:
    image: mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest
    pull_policy: always
    volumes:
      - "${EVENTHUB_CONFIG_PATH}:/Eventhubs_Emulator/ConfigFiles/Config.json"
    environment:
      # Event Hub Emulator Configuration
      - ACCEPT_EULA=Y
      - BLOB_SERVER=azurite
      - METADATA_SERVER=azurite
    ports:
      - "5673:5672"  # AMQP protocol
      - "9092:9092"  # Kafka protocol
      - "5301:5300"  # Management endpoint
    depends_on:
      - azurite
    networks:
      - azure-emulator-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002"
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service  
      - "10002:10002" # Table service
    volumes:
      - azurite-data:/data
    networks:
      - azure-emulator-network

volumes:
  servicebus-data:
  azurite-data:
  sqlserver-data:

networks:
  azure-emulator-network:
    driver: bridge